default: &default
  adapter: postgresql
  encoding: unicode
  username: nakul
  password: <%= ENV['POSTGRES_APP_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: postgres_app_development

test:
  <<: *default
  database: postgres_app_test

production:
  <<: *default
  database: postgres_app_production
